filebeat.registry.path: /usr/share/filebeat/data/registry


filebeat.config.inputs:
  path: ${path.config}/prospectors.d/*.yml
  reload.enabled: false


filebeat.modules:

#Filebeat system module consumes logs from host OS through a mounted volume.
- module: system
  syslog:
    var.paths: ["/var/log/host/system.log*"]

monitoring.enabled: true

output.elasticsearch:
  hosts: ["192.168.99.15:9200"]

logging.to_files: false

setup:
  kibana.host: "192.168.99.15:5601"
  dashboards.enabled: true
