version: '3.5'

services:

  #Metricbeat container
  metricbeat:
    container_name: metricbeat-${HOST_NAME}
    hostname: metricbeat-${HOST_NAME}
    user: root #To read the docker socket
    image: docker.elastic.co/beats/metricbeat-oss:${ELASTIC_VERSION}
    command: metricbeat -e -system.hostfs=/hostfs -strict.perms=false
    volumes:
      #Mount the metricbeat configuration so users can make edits.
      - ./config/beats/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      #Mount the modules.d directory into the container. This allows user to potentially make changes to the modules and they will be dynamically loaded.
      - ./config/beats/metricbeat/modules.d/:/usr/share/metricbeat/modules.d/
      #The commented sections below enable Metricbeat to monitor the Docker host rather than the Metricbeat container. These are used by the system module.
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      #Allows us to report on docker from the hosts information.
      - /var/run/docker.sock:/var/run/docker.sock
      #We mount the host filesystem so we can report on disk usage with the system module.
      - /:/hostfs:ro
    restart: on-failure
    networks:
      - elk-ciomss

  #Auditbeat container
  auditbeat:
    container_name: auditbeat-${HOST_NAME}
    hostname: auditbeat-${HOST_NAME}
    user: root #To read the docker socket
    image: "docker.elastic.co/beats/auditbeat-oss:${ELASTIC_VERSION}"
    command: auditbeat -e -strict.perms=false
    volumes:
      #Mount the Auditbeat configuration so users can make edits.
      - ./config/beats/auditbeat/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml
      #Allows us to report on docker from the hosts information.
      - /var/run/docker.sock:/var/run/docker.sock
    pid: "host" # Set the required permissions with pid and cap_add for Auditbeat
    cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']
    restart: on-failure
    networks:
      - elk-ciomss

  #Heartbeat container
  heartbeat:
    container_name: heartbeat-${HOST_NAME}
    hostname: heartbeat-${HOST_NAME}
    user: root #To read the docker socket
    image: "docker.elastic.co/beats/heartbeat-oss:${ELASTIC_VERSION}"
    command: heartbeat -e -strict.perms=false
    volumes:
      #Mount the Heartbeat configuration so users can make edits.
      - ./config/beats/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
      #Allows us to report on docker from the hosts information.
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    networks:
      - elk-ciomss

  #Packetbeat container
  packetbeat:
    container_name: packetbeat-${HOST_NAME}
    hostname: packetbeat-${HOST_NAME}
    user: root #To read the docker socket
    image: "docker.elastic.co/beats/packetbeat-oss:${ELASTIC_VERSION}"
    command: packetbeat -e -strict.perms=false
    volumes:
      #Mount the packetbeat configuration so users can make edits.
      - ./config/beats/packetbeat/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
      #Allows us to report on docker from the hosts information.
      - /var/run/docker.sock:/var/run/docker.sock
    # Packetbeat needs some elevated privileges to capture network traffic. We'll grant them with POSIX capabilities.
    cap_add: ['NET_RAW', 'NET_ADMIN']
    # Use "host mode" networking to allow Packetbeat to capture traffic from the real network interface on the host,
    # rather than being isolated to the container's virtual interface.
    network_mode: host
    restart: on-failure

volumes:
  filebeatdata:
    driver: local

networks:
  elk-ciomss:
    driver: bridge
    name: elk-ciomss
    external: false
