metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: true


processors:
- add_docker_metadata: ~


monitoring.enabled: true


output.elasticsearch:
  hosts: ["192.168.99.15:9200"]


logging.to_files: false


setup:
  kibana.host: "192.168.99.15:5601"
  dashboards.enabled: true
